apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
      annotations: 
        # This annotation will change on every Helm upgrade, forcing a new rollout
        deployment.kubernetes.io/revision: "{{ .Release.Revision }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 50051
        env:
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: EMAIL
        - name: SUPER_SECRET
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: SUPER_SECRET
