apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      annotations: 
        # This annotation will change on every Helm upgrade, forcing a new rollout
        deployment.kubernetes.io/revision: "{{ .Release.Revision }}"
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.port }}
        livenessProbe:
          grpc:
            port: {{ .Values.deployment.port }}
          initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
          periodSeconds: {{ .Values.health.periodSeconds }}
        readinessProbe:
          grpc:
            port: {{ .Values.deployment.port }}
          initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
          periodSeconds: {{ .Values.health.periodSeconds }}
        env:
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: EMAIL
        - name: SUPER_SECRET
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: SUPER_SECRET
