apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  EMAIL: {{ .Values.secrets.email | default "" }}
  SUPER_SECRET: {{ .Values.secrets.superSecret | default "" }}
