apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  labels:
    app: {{ .Values.deployment.name }}
type: Opaque
data:
  EMAIL: {{ .Values.secrets.email | default "" }}
  SUPER_SECRET: {{ .Values.secrets.superSecret | default "" }}
