deployment:
  name: notification
  replicas: 1
  image: rsocontainerregistry.azurecr.io/notification:v1
  port: 50051

secrets:
  email: bWF0ZWoua292YWNAbWFpbC5jb20=  # Base64 encoded value of "kovacmateomatejci@gmail.com"
  superSecret: a21wciBnYXJxIGhncGMgcnNldQ==  # Base64 encoded value of "kmpr garq hgpc rseu"